version: '3'

services:
  db:
    container_name: postgres_database
    image: postgres:15.3
    volumes:
      # - postgres-db:/var/lib/postgresql/data # ejemplo
      - ./Docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456

  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:7.5
    ports:
      - "8080:80"
    volumes:
      - ./Docker/pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456 
      - PGADMIN_DEFAULT_EMAIL=afva@gmail.com

# volumes:
#   postgres-db:
#     external: true